#### NumPy (aka Numerical Python) 

    is a fundamental library for scientific computing in Python. 
    
    It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures &focuses on arrays and vectorized operations.
    
    
#### Common functions used:
           
1- .array()  

2- .shape \
ex: arr.shape

3- .reshape()

4- .arange()

5- .ones(row, col)

6- .zeros(row, col)

7- .eye()

8- .ndim \
ex: arr.ndim

9- .size

10- .dtype

11- .itemsize

12- .sqrt()

13- .exp() \
exponential

14- .sin()

15- .log()

16- .mean(data) \
data could be anything

17- .std(data)

18- .median(data)

19- .var(data) \
variance

20- .random().randint()

21- .random().randn()

22- .random().random_sample()

In [65]:
num_list: list[int] = [1, 3, 7, 9, 13]
print(num_list)
print(type(num_list))

[1, 3, 7, 9, 13]
<class 'list'>


In [66]:
import numpy as np

In [67]:
arr_1 = np.array(num_list)                # also can be written as  np.array( [1, 3, 7, 9, 13] )
print(arr_1)                # prints [ 1  3  7  9 13]
print(arr_1.shape)           # prints (5,) means 1D array having 5 elements

print('\n', type(arr_1))

[ 1  3  7  9 13]
(5,)

 <class 'numpy.ndarray'>


In [68]:
# reshape to a 2D array
print(arr_1.reshape(1, 5))              # prints a 2D array [[ 1  3  7  9 13]] means 1 row & 5 columns
print(arr_1.reshape(1, 5, 1))            # prints  a 3D array with 5 rows and  1 column

print(arr_1)                    # prints [ 1  3  7  9 13] - changes won't be saved

[[ 1  3  7  9 13]]
[[[ 1]
  [ 3]
  [ 7]
  [ 9]
  [13]]]
[ 1  3  7  9 13]


In [69]:
# create 2D array directly
arr_2 = np.array([ num_list ])                # also can be written as np.array([ [1, 3, 7, 9, 13] ])
print(arr_2)
print(arr_2.shape)                      # prints (1, 5) means 1 row and 5 columns

[[ 1  3  7  9 13]]
(1, 5)


In [70]:
list_1: list[int] = [1, 2, 3, 4, 5]
list_2: list[int] = [3, 4, 5, 6, 7]
list_3: list[int] = [7, 9, 11, 13, 19]              # ensure rows & cols count/size should be same

arr_from_list = np.array([ list_1, 
          list_2, 
          list_3] )                     # prints 3 x 5 matrix

print(arr_from_list)
print(arr_from_list.size)               # size of 3 x 5 matrix = 15

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 7  9 11 13 19]]
15


In [71]:
arr_3 = np.array([ [2, 3, 5, 6],
                                [7, 9, 11, 21] ])

# Attributes of Numpy Array
print(f'Array: {arr_3}\n')
print(f'Shape of array: {arr_3.shape}\n')              # prints (2,4) means 2 row & 4 columns
print(f'Number of dimensions: {arr_3.ndim}\n') 
print(f'Size aka no. of elements: {arr_3.size}\n') 
print(f'Data type of array: {arr_3.dtype}\n') 
print(f'Item size (in bytes) of array: {arr_3.itemsize}\n') 

Array: [[ 2  3  5  6]
 [ 7  9 11 21]]

Shape of array: (2, 4)

Number of dimensions: 2

Size aka no. of elements: 8

Data type of array: int64

Item size (in bytes) of array: 8



#### other ways to create array

            - via .arange([start],  [stop],  [step]) function

In [72]:
np.arange(0, 10, 2)         # means start from 0, go till 10 but skip 10 and jump every 2 nos. - 0, 2, 4....

array([0, 2, 4, 6, 8])

In [73]:
# reshaping similar array to 2D
np.arange(0, 10, 2).reshape(5, 1)         # since there are 5 elements in array, hence reshaping can be done in multiples of 5 either in 5 x 1 (or) 1 x 5

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [74]:
np.ones((3, ))          # means create 1D array with 3 elements - all with values = 1

array([1., 1., 1.])

In [75]:
np.ones((3, 4))          # means create 2D array with 3 rows and 4 cols - all with values = 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.zeros((3, 4))             # means create 2D array with 3 rows and 4 cols - all with values = 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
# create identity matrix
print(np.eye(3))               # creates a sqaure matrix of 3 x 3 (3 rows, 3 cols) which has 1 inserted diagonally
print(np.eye(2))               # creates a sqaure matrix of 2 x 2 (2 rows, 2 cols) which has 1 inserted diagonally

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


#### Numpy Vectorized oeprations

In [78]:
num_1 = np.array([2, 4, 6, 8])
num_2 = np.array([7, 1, 3, 4])

print('Adding 2 arrays:', num_1 + num_2)
print('Subtracting 2 arrays:', num_1 - num_2)
print('Multiplying 2 arrays:', num_1 * num_2)
print('Multiplying num_1 array with 3:', num_1 * 3)

print('Dividing 2 arrays:', num_1 / num_2)

Adding 2 arrays: [ 9  5  9 12]
Subtracting 2 arrays: [-5  3  3  4]
Multiplying 2 arrays: [14  4 18 32]
Multiplying num_1 array with 3: [ 6 12 18 24]
Dividing 2 arrays: [0.28571429 4.         2.         2.        ]


#### Universal functions

        are the functions which applies to the entire array

In [79]:
num_4 = np.array([9, 16, 64, 81, 100])

# square root
print(np.sqrt(num_4))

# exponential like 8^8
print(np.exp(num_1))                    # num_1 = np.array([2, 4, 6, 8])

# Sine
print(np.sin(num_1))

# natural log
print(np.log(num_1))

[ 3.  4.  8.  9. 10.]
[   7.3890561    54.59815003  403.42879349 2980.95798704]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]
[0.69314718 1.38629436 1.79175947 2.07944154]


#### Array slicing and indexing     [VERY IMPORTANT]

In [80]:
# pick last & 2nd last element
# arr_1 was defined above as        [ 1  3  7  9 13]

print(arr_1[-1])            # -1 means pick last element only i.e, 13
print(arr_1[-2])            # -2 means pick 2nd last element only i.e, 9

# single colon : with -1 means start from 0th index and go till -1 (which is last element) and skip last element
print(arr_1[:-1])                   # prints [1 3 7 9]

print(arr_1[:-2])                   # prints [1 3 7] - skipped the last 2 elements

13
9
[1 3 7 9]
[1 3 7]


In [81]:
# reverse the array
print(arr_1[::-1])                 # prints array([13,  9,  7,  3,  1])

# print from back but jump / skip 1 element
print(arr_1[::-2])                          # prints [13  7  1]

[13  9  7  3  1]
[13  7  1]


In [103]:
# Slicing operations on multi-dimensional arrays

num_5 = np.array([ [2, 3, 5, 6],                # 3 x 4 matrix
                  [11, 7, 9, 0],
                  [1, 8, -1, 12],
])
print(num_5)


[[ 2  3  5  6]
 [11  7  9  0]
 [ 1  8 -1 12]]


In [108]:
# pick only 9 8
print(f'{num_5[1, 2]}\n{num_5[2, 1]}')

9
8


In [96]:
# pick 1st col values only i.e, 3 7 8 (vertically)
num_5[:, [0, -1]]                 # : means take all rows, [0, -1] means just take 0th col and -1 col

array([[ 2,  6],
       [11,  0],
       [ 1, 12]])

In [84]:
# assignment asked - pick 2 11 1 and 6 0 12
num_5[:, 3]

array([ 6,  0, 12])

In [85]:
# pick 0th row
print(num_5[0])

# pick 0th row 0th element
print(num_5[0][0])


# pick elements: 9 0 -1 12
print(num_5[1:, 2:])                 # gone from 1st row and 2nd col till end


# pick elements: 5 6 9 0 
print(num_5[0:2, 2:])                 # gone from 0th - 1st row and 2nd col till end


# pick elements: 7 9 8 -1 
print(num_5[1:, 1:3])

[2 3 5 6]
2
[[ 9  0]
 [-1 12]]
[[5 6]
 [9 0]]
[[ 7  9]
 [ 8 -1]]


In [86]:
# modify array elements
num_5[0, 0] = 100
num_5[2, 3] = -212

# num_5[2] = 90               # beware - this will change all elements of row 3

print(num_5)

num_5[1:] = 0               # beware - changes all elements from 1st row till end
print(num_5)

[[ 100    3    5    6]
 [  11    7    9    0]
 [   1    8   -1 -212]]
[[100   3   5   6]
 [  0   0   0   0]
 [  0   0   0   0]]


#### Logical Operations

               - mainly used for EDA aka Exploratory Data Analysis

In [87]:
data = np.array([2, 4, 6, 7, 4, 9, 0, 11, 13, 5])

data > 5

array([False, False,  True,  True, False,  True, False,  True,  True,
       False])

In [88]:
# retrieve all elements greater than 5
print(data[data > 5])

# retrieve all elements greater than 5 and less than 10 - parenthesis is SUPER important
print(data[ (data > 5) 
           & (data < 10)
           ])

[ 6  7  9 11 13]
[6 7 9]


In [89]:
print(np.random.randint(10, 50))       # initializes a random number between 10 & 50 each time when run

print(np.random.randint(10, 50, 4))        # 4 is the size which means it will create an array of 4 elements now

49
[24 31 38 24]


In [90]:
np.random.random_sample((4,3))          # creates a 4 x 3 matrix array of 1 < nos > -1

array([[0.18983761, 0.55115729, 0.33600182],
       [0.37554289, 0.49062386, 0.34594219],
       [0.79727876, 0.45698877, 0.62428436],
       [0.02050357, 0.6292971 , 0.19382063]])

#### Statistical concept aka "**Normalization**"

- to have a mean of **0** and standard deviation of **1**  

        (may not be required for MLOps - hence parked for now)

In [91]:
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)

std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev

print('Normalized data:', normalized_data)              # Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [92]:
# mean, median, mode - LEFT for now